-- MySQL Script generated by MySQL Workbench
-- 08/16/21 18:34:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdmysistvendas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdmysistvendas` ;

-- -----------------------------------------------------
-- Schema bdmysistvendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdmysistvendas` DEFAULT CHARACTER SET latin1 ;
USE `bdmysistvendas` ;

-- -----------------------------------------------------
-- Table `bdmysistvendas`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmysistvendas`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `bdmysistvendas`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `unidade` VARCHAR(10) NOT NULL,
  `vlUnitario` DOUBLE NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdmysistvendas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmysistvendas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `bdmysistvendas`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` CHAR NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdmysistvendas`.`CuponsFiscais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmysistvendas`.`CuponsFiscais` ;

CREATE TABLE IF NOT EXISTS `bdmysistvendas`.`CuponsFiscais` (
  `ccf` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `formaPagamento` INT NOT NULL,
  `vlTotal` DOUBLE NOT NULL,
  `fk_idCliente` INT NOT NULL,
  PRIMARY KEY (`ccf`),
  INDEX `fk_CupomFiscal_Cliente1_idx` (`fk_idCliente` ASC),
  CONSTRAINT `fk_CupomFiscal_Cliente1`
    FOREIGN KEY (`fk_idCliente`)
    REFERENCES `bdmysistvendas`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdmysistvendas`.`ItensCupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmysistvendas`.`ItensCupom` ;

CREATE TABLE IF NOT EXISTS `bdmysistvendas`.`ItensCupom` (
  `fk_ccf` INT NOT NULL,
  `fk_idProduto` INT NOT NULL,
  `nItem` INT NOT NULL,
  `qtd` INT NOT NULL,
  `vlItem` DOUBLE NOT NULL,
  PRIMARY KEY (`fk_ccf`, `fk_idProduto`, `nItem`),
  INDEX `fk_ItemCupom_Produto_idx` (`fk_idProduto` ASC),
  INDEX `fk_ItemCompra_CupomFiscal_idx` (`fk_ccf` ASC),
  CONSTRAINT `fk_ItemCupom_Produto`
    FOREIGN KEY (`fk_idProduto`)
    REFERENCES `bdmysistvendas`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemCompra_CupomFiscal`
    FOREIGN KEY (`fk_ccf`)
    REFERENCES `bdmysistvendas`.`CuponsFiscais` (`ccf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
